version: '3.8'
services:
  db:
    container_name: ${CONTAINER_PREFIX}_${ENV}
    image: mysql:5.7
    restart: always
    env_file:
      - .env
    ports:
      - '$PORT:3306'
    volumes:
      - db:/var/lib/mysql
volumes:
  db:
    driver: local